# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TairuDB
                                 A QGIS plugin
 Cria bases de dados gograficos para o aplicativo Tairu Maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-19
        copyright            : (C) 2025 by Daniel Hulshof Saint Martin
        email                : daniel.hulshof@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Daniel Hulshof Saint Martin'
__date__ = '2025-05-19'
__copyright__ = '(C) 2025 by Daniel Hulshof Saint Martin'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TairuDB class from file TairuDB.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tairu_db import TairuDBPlugin
    return TairuDBPlugin(iface)
